// An empty runtime class needs a [default_interface] tag to indicate that the 
// emptiness is intentional.
import "MainViewModel.idl";

namespace DialogServiceWinUI
{
    [default_interface]
    runtimeclass MainPage : Microsoft.UI.Xaml.Controls.Page
    {
        MainPage();

        MainViewModel ViewModel{ get; };

        Double NavViewCompactModeThresholdWidth{ get; };
    }
}
